repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"

  - repo: https://github.com/psf/black
    rev: 21.11b0
    hooks:
    - id: black

  - repo: https://github.com/dfm/black_nbconvert
    rev: v0.3.0
    hooks:
      - id: black_nbconvert
